<h1><center>4절. 데이터 구조 & 데이터 프레임</center></h1>

## 1. [Vector 벡터]

### 1_1. 벡터
1. **[Homogenous 동질적]** : 모든 원소는 같은 자료형 또는 모드.
1. 위치로 인덱스, 하위벡터 생성 가능, 원소들은 이름을 가질 수 있음.

In [9]:
V <- c(10,20,30); names(V) <- c('ten', 'twenty', 'thrity')
V[1]; V['twenty']

ten 
 10

twenty 
    20

## 2. [List 리스트]

### 2_1. 리스트
1. **[Heterogenous 이질적]** : 각 원소는 다른 자료형 또는 모드 가능.
1. 위치로 인덱스, 하위벡터 생성 가능, 원소들은 이름을 가질 수 있음.

In [8]:
L <- list(10,'BB', pi); names(L) <- c('ten', 'BB', 'pi')
L[2]; L$"pi"

$BB
[1] "BB"

[1] 3.141593

## 3. R에서의 자료형태

### 3_1. mod
1. **numeric** : 수치형(1, 2, 3), 수치형 벡터(c(1, 2, 3)), 요인(factor(c('A', 'B', 'C')))
1. **character** : 문자열('Jang'), 문자형 벡터(c('Jang', 'Eun', 'Chul'))
1. **list** : 리스트(list('Jang', 'Eun', 'Chul')), 데이터프레임(data.frame(x=1:3, y=c('one', 'two', 'three')))
1. **function** : 함수(print(), cat())

## 4. 데이터 프레임

### 4_1. 데이터 프레임
**SAS 데이터셋**을 모방해서 만들었으며 엑셀의 시트와 같은 역할을 한다. **메모리상에서 구동**되며 각 열마다 다른 자료형을 입력할 수 있다.
- 데이터 프레임의 원소는 벡터나 요인
- 각 벡터와 요인들은 동일한 길이를 가짐
- 열에는 이름이 있어야 함

In [31]:
df <- data.frame(x=1:3, y=c('A', 'B', 'C'))
df[1]; df['x']
df[[1]]; df[[1]]
df$x

x
1 1
2 2
3 3

x
1 1
2 2
3 3

[1] 1 2 3

[1] 1 2 3

[1] 1 2 3

## 5. 그 밖의 구조들

### 5_1. 그 밖의 구조들
1. **[Scalars 단일값]** : 원소가 하나인 벡터
1. **[Matrix 행렬]** : 차원을 가진 벡터
1. **[Array 배열]** : 행렬에 3차원 또는 n차원까지 확장된 형태
1. **[Factors 요인]** : 벡터 내의 고윳값들, 교윳값을 **요인의 수준**이라고 함

In [40]:
b <- 1:12
dim(b) <-c(4,3)
b

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

## 6. 벡터, 리스트, 행렬 다루기

### 6_1 관련 기능들
행렬은 차원을 가진 벡터이다. 빈값을 자동을 채워서 계산하는 [Recycling Rule 재활용 규칙]이 적용된다.

In [47]:
a <- seq(1,6)
b <- seq(7,9)
cbind(a, b) # 비어있는 값이 자동으로 생성됨.

a b
[1,] 1 7
[2,] 2 8
[3,] 3 9
[4,] 4 7
[5,] 5 8
[6,] 6 9

In [79]:
v <- c(1, 2, 3, 4, 5); v

# 벡터에 데이터 추가
v <- c(v, 6, 7, 8); v
v[length(v) + 1] <- 9; v

# 벡터에 데이터 삽입
append(v, c(5, 5, 5), after = 5)

# 요인 생성
f <- factor(v)
f

# 리스트 생성
l <- list('txt'=c('A', 'B'), 'num'=c(1, 2)); l

# 리스트 원소 선택
l[[1]]; l$num

# 리스트에서 원소 제거
l[[1]] <- NULL

# Null을 리스트에서 제거
l[is.na(l)] <- NULL

[1] 1 2 3 4 5

[1] 1 2 3 4 5 6 7 8

[1] 1 2 3 4 5 6 7 8 9

[1] 1 2 3 4 5 5 5 5 6 7 8 9

[1] 1 2 3 4 5 6 7 8 9
Levels: 1 2 3 4 5 6 7 8 9

$txt
[1] "A" "B"

$num
[1] 1 2

[1] "A" "B"

[1] 1 2

In [114]:
# 행렬 만들기
print('행렬 만들기')
m <- matrix(1:15, 3, 5); m

# 차원 설정
print('차원 설정')
n <- 1:6; dim(n) <- c(2,3); n

# 대각 행열
print('대각 행렬'); diag(m)

# 전치 행열
print('전치 행렬'); t(m)

# 역
A = matrix(c(2,1,0,1,2,1,0,1,2),ncol=3)
P = matrix(c(1,0,0,0,0,1,0,1,0),ncol=3)
B=P%*%A
print('역행렬'); 
solve(B)

[1] "행렬 만들기"


[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

[1] "차원 설정"


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] "대각 행렬"


[1] 1 5 9

[1] "전치 행렬"


[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12  
[5,] 13   14   15

[1] "역행렬"


[,1]  [,2]  [,3]
[1,]  0.75  0.25 -0.5
[2,] -0.50 -0.50  1.0
[3,]  0.25  0.75 -0.5

In [124]:
# 행렬의 곱
print('행렬의 곱');  B=P%*%A; B

# 행렬에 이름 부여
print('행렬에 이름 부여');
colnames(A) <- c('A1', 'A2', 'A3')  # 열 이름
rownames(A) <- c('x1', 'x2', 'x3')  # 행 이름
A

# 행열에서 선택
vec <- B[1,] ; vec  # 1번째 열을 선택
vec <- B[, 3]; vec  # 3번째 행을 선택

[1] "행렬의 곱"


A1 A2 A3
[1,] 2  1  0 
[2,] 0  1  2 
[3,] 1  2  1

[1] "행렬에 이름 부여"


A1 A2 A3
x1 2  1  0 
x2 1  2  1 
x3 0  1  2

A1 A2 A3 
 2  1  0

[1] 0 2 1